version: '3.8'
services:
  imdb_scrapper:
    image: 'imdb_scrapper'
    build:
      context: "./"
      dockerfile: "Dockerfile"
    volumes:
      - "/root/programming/imdb_scrapper_async/database:/imdb_scrapper_async/database"
      - "/root/programming/imdb_scrapper_async/data:/imdb_scrapper_async/data"
      - "/root/programming/imdb_scrapper_async/lib:/imdb_scrapper_async/lib"
  imdb_api:
    image: 'imdb_api'
    depends_on:
      - imdb_scrapper
    ports:
      - "8000:8000"
    build:
      context: "./imdb_api/"
      dockerfile: "Dockerfile"
    volumes:
      - "/root/programming/imdb_scrapper_async/database:/imdb_api/database"
      - "/root/programming/imdb_scrapper_async/lib:/imdb_api/lib"
volumes:
    imdb_scrapper: